Committed current scripts

diff --git a/src/clipvideo b/src/clipvideo
--- a/src/clipvideo
+++ b/src/clipvideo
@@ -20,10 +20,12 @@ process_option(){
 	VALUE="$2"
 	case "$NAME" in
 		subs)
-			if [ "x$VALUE" = "xyes" ] ; then
-				SUBS="yes"
+			if [ "x$VALUE" = "xhard" ] ; then
+				SUBS="hard"
 			elif [ "x$VALUE" = "ximage" ] ; then
 				SUBS="image"
+			elif [ "x$VALUE" = "xsoft" ] ; then
+				SUBS="soft"
 			fi
 			;;
 		aid)
@@ -42,15 +44,15 @@ process_option(){
 			case "$VALUE" in
 				nvenc)
 					ENCODER="h264_nvenc"
-					FORMAT="yuv420p"
+					FORMAT="nv12"
 					;;
 				h264)
 					ENCODER="h264_nvenc"
-					FORMAT="yuv420p"
+					FORMAT="nv12"
 					;;
 				h264_nvenc)
 					ENCODER="h264_nvenc"
-					FORMAT="yuv420p"
+					FORMAT="nv12"
 					;;
 				hevc)
 					ENCODER="hevc_nvenc"
@@ -91,17 +93,22 @@ process_option(){
 		filter)
 			FILTER="$VALUE"
 			;;
+		pause)
+			>&2 echo "Warning: Ignoring --pause"
+			;;
 		*)
-			echo "Invalid option: $NAME=$VALUE" >&2
+			>&2 echo "Invalid option: $NAME=$VALUE"
 			exit 1
 			;;
 	esac
 }
 
 for arg; do
-	if [[ "x$ARGSDONE" != "xyes" && "x$arg" =~ ^x-- ]] ; then
+	if [[ "x$ARGSDONE" != "xyes" && "$arg" =~ ^-- ]] ; then
 		if [ "x$arg" = "x--" ] ; then
 			ARGSDONE="yes"
+		elif [[ ! "$arg" =~ = ]] ; then
+			process_option "${arg#--}" "${arg#--}"
 		else
 			process_option "$(sed 's/^--\([^=]*\)=\(.*\)$/\1/' <<<"$arg")" "$(sed 's/^--\([^=]*\)=\(.*\)$/\2/' <<<"$arg")"
 		fi
@@ -142,7 +149,7 @@ DURATION="$(awk '{ print $2 - $1 }' <<<"$STARTSECS $ENDSECS")"
 
 subslink=".clipvideo_subsymlink"
 
-if [ "x$SUBS" = "xyes" ] ; then
+if [ "x$SUBS" = "xhard" ] ; then
 	rm -f "$subslink"
 	ln -s "$VIDEOINPUT" "$subslink"
 	FILTER="subtitles=filename=$subslink:si=$SID,$FILTER"
@@ -155,9 +162,11 @@ if [[ "$VIDEOOUTPUT" =~ \.(mkv|MKV)$ ]] ; then
 	FORMATOPTS="-live 1"
 elif [[ "$VIDEOOUTPUT" =~ \.(ts|TS)$ ]] ; then
 	AUDIOOPTS="-c:a libopus -b:a 128k"
+elif [[ "$VIDEOOUTPUT" =~ \.(nut|NUT)$ ]] ; then
+	AUDIOOPTS="-c:a libopus -b:a 128k"
 elif [[ "$VIDEOOUTPUT" =~ \.(mp4|MP4)$ ]] ; then
 	FORMATOPTS="-movflags +faststart"
-	AUDIOOPTS="-c:a aac -b:a 128k"
+	AUDIOOPTS="-c:a libfdk_aac -b:a 128k"
 else
 	AUDIOOPTS="-c:a libvorbis -q:a 5"
 fi
@@ -168,7 +177,7 @@ if [ "x$BITRATE" = "xvbr" ] ; then
 			BITRATEOPTS="-crf:v 18"
 			;;
 		*)
-			BITRATEOPTS="-global_quality:v 15"
+			BITRATEOPTS="-qp:v 15"
 			;;
 	esac
 else
@@ -195,9 +204,17 @@ case "$ENCODER" in
 esac
 
 if [ "x$SUBS" = "ximage" ] ; then
+	set -x
 	ffmpeg -ss "$START" -copyts -start_at_zero -i "$VIDEOINPUT" -lavfi "[0:v][0:s:${SID}]overlay,${FILTER}[v]" -map "[v]" -map "$AUDIOSTREAM" -t "$DURATION" -af "asetpts=PTS-STARTPTS" $VIDEOOPTS $BITRATEOPTS $AUDIOOPTS $FORMATOPTS $FFOPTS -y "$VIDEOOUTPUT"
+	2>/dev/null set +x
+elif [ "x$SUBS" = "xsoft" ] ; then
+	set -x
+	ffmpeg -ss "$START" -copyts -start_at_zero -i "$VIDEOINPUT" -map "$VIDEOSTREAM" -map "$AUDIOSTREAM" -map s? -map t? -map d? -c copy -t "$DURATION" -vf "$FILTER" -af "asetpts=PTS-STARTPTS" $VIDEOOPTS $BITRATEOPTS $AUDIOOPTS $FORMATOPTS $FFOPTS -y "$VIDEOOUTPUT"
+	2>/dev/null set +x
 else
+	set -x
 	ffmpeg -ss "$START" -copyts -start_at_zero -i "$VIDEOINPUT" -map "$VIDEOSTREAM" -map "$AUDIOSTREAM" -t "$DURATION" -vf "$FILTER" -af "asetpts=PTS-STARTPTS" $VIDEOOPTS $BITRATEOPTS $AUDIOOPTS $FORMATOPTS $FFOPTS -y "$VIDEOOUTPUT"
+	2>/dev/null set +x
 fi
 
 rm -f "$subslink"
diff --git a/src/exsorttar b/src/exsorttar
--- a/src/exsorttar
+++ b/src/exsorttar
@@ -27,7 +27,8 @@ usage(){
 	echo "                            You may specify --tararg multiple times to add multiple arguments."
 	echo "                            Example: --tararg=-z"
 	echo "    --lz4                   Compress the tar archive with lz4 HC (requires the lz49 script)."
-	echo "    --force                 Overwrite regular files without asking."
+	echo "    --force                 Don't ask questions before making decisions."
+	echo "                            This is particularly useful in a script, but not recommended for interactive use."
 	echo ""
 	echo "You are required to give the tar archive filename unless --no-tar is specified."
 	echo "Pass '-' as the archive name to write the archive to standard out."
@@ -81,6 +82,9 @@ for i; do
 			force=true
 		elif [ "$i" == "--no-tar" ] ; then
 			notar=true
+		elif [ "$i" == "--" ] ; then
+			foundfirst=true
+			continue
 		else
 			foundfirst=true
 		fi
@@ -97,12 +101,20 @@ for i; do
 	fi
 done
 
-# what if they don't give us anything?
+# what if they don't give us anything at all?
 if ! $notar && [ -z "$tarfile" ]; then
-	echo "Error: no archive name on command line, and no --no-tar."
+	echo "Error: No archive name on command line, and no --no-tar."
 	minorusage
 	exit 1
 fi
+
+# what if they don't give us anything to archive?
+if ! $notar && [ -z "${filelist[0]}" ]; then
+	echo "Error: No list of files provided. Provide '.' to archive the current directory."
+	minorusage
+	exit 1
+fi
+
 
 # This failsafe works especially well at detecting when people forgot the archive name and jumped right to a list of dirs.
 if ! $notar && [ -d "$tarfile" ] ; then
@@ -113,26 +125,22 @@ if ! $notar && [ -d "$tarfile" ] ; then
 fi
 
 # doublecheck the file arguments
-foundminus=false
-for f in ${filelist[@]}; do 
+# foundminus=false
+for f in "${filelist[@]}"; do 
 	if [[ "$f" =~ ^- ]] ; then
-		echo "Warning: Interpreting $f as a file/directory name. Press Ctrl+C if you didn't mean this."
-		foundminus=true
+		echo "Error: Interpreting $f as a file or directory name. This can break \`find\`. Use ./$f to supress this error."
+		exit 1
 	fi
 	if [ ! -e "$f" ] ; then
-		echo "Error: $f: no such file or directory"
+		echo "Error: $f: No such file or directory."
 		exit 1
 	fi
 done
 
-# Give them time to Ctrl+C
-if $foundminus; then sleep 1; fi
-
-# Allow the user to take back typos. Does not stop block devices because that's just annoying.
+# Allow the user to take back typos. Does not stop on devices because that's just annoying.
 if ! $force && ! $notar && [ -f "$tarfile" ]; then
 	if [ -t 0 ] ; then
-		echo -n "Tar archive, $tarfile, already exists. Overwrite? [y/N]: "
-		read line
+		read -p "Tar archive, $tarfile, already exists. Overwrite? [y/N]: " line
 		if ! [[ "$line" =~ ^y|Y ]]; then
 			echo "Not overwriting $tarfile."
 			exit 1
@@ -145,13 +153,13 @@ fi
 
 # this uses the lz49 script. It's essentially a wrapper for lz4 with -9 attached, because tar -I doesn't let us pass options.
 if $lz4; then
-	if ! lz49 -z - - </dev/null >/dev/null 2>/dev/null; then
-		echo "lz49 not found in PATH."
-		echo "Add the lz49 script to use --lz4."
+	if ! lz4 -9 -z - - </dev/null >/dev/null 2>/dev/null; then
+		echo "lz4 not found in PATH."
+		#echo "Add the lz49 script to use --lz4."
 		exit 2
 	fi
 	tarargs+=("-I")
-	tarargs+=("lz49")
+	tarargs+=("lz4 -9 -z")
 fi
 
 # alright, let's get to it!
@@ -161,12 +169,12 @@ sortbyext(){
 }
 
 printfilelist(){
-	cat <(find ${filelist[@]} ${findargs[@]} -type d | sort -t/) <(find ${filelist[@]} ${findargs[@]} -type f | sortbyext) <(find ${filelist[@]} ${findargs[@]} -not -type d -and -not -type f | sort -t/)
+	cat <(find "${filelist[@]}" "${findargs[@]}" -type d | sort -t/) <(find "${filelist[@]}" "${findargs[@]}" -type f | sortbyext) <(find "${filelist[@]}" "${findargs[@]}" -not -type d -and -not -type f | sort -t/)
 }
 
 if $notar; then
 	printfilelist
 else
-	tar --no-recursion -T <(printfilelist) ${tarargs[@]} -cvf "$tarfile"
+	tar --no-recursion -T <(printfilelist) "${tarargs[@]}" -cvf "$tarfile"
 fi
 
