exsorttar version 1.0-RC1

diff --git a/src/exsorttar b/src/exsorttar
--- a/src/exsorttar
+++ b/src/exsorttar
@@ -1,15 +1,21 @@
 #!/bin/bash 
 set -e
+shopt -s expand_aliases
+alias echo='>&2 echo'
+
+minorusage() {
+	echo "Usage:" "$(basename $0) [options] [archive.tar] file_or_directory..."
+}
 
 usage(){
-	echo "Usage:" "$(basename $0) [options] [archive.tar] file_or_directory..."
+	minorusage
 	echo
 	echo "exsorttar will take a list of files and directories and recurse through with the find command."
 	echo
 	echo "It will create a tar archive with directories first (sorted by name, starting with the top directories), followed by regular files (sorted by file extension, then by filename, then by directory name), followed by everything else (including symbolic links, etc.)"
 	echo ""
 	echo "Options:"
-	echo "    -h,-?,--help            Print this help message."
+	echo "    --help,-h,-?            Print this help message."
 	echo "    --no-tar                Do not create an archive."
 	echo "                            Instead, print the file list in order to standard out."
 	echo "    --findarg=<findargs>    Add <findarg> as an argument to the find command."
@@ -33,7 +39,7 @@ usage(){
 }
 
 # people like not having to type --help again
-if [ $# -le 1 ] ; then
+if [ $# -eq 0 ] ; then
 	usage 1
 fi
 
@@ -94,8 +100,16 @@ done
 # what if they don't give us anything?
 if ! $notar && [ -z "$tarfile" ]; then
 	echo "Error: no archive name on command line, and no --no-tar."
-	echo ""
-	usage 1
+	minorusage
+	exit 1
+fi
+
+# This failsafe works especially well at detecting when people forgot the archive name and jumped right to a list of dirs.
+if ! $notar && [ -d "$tarfile" ] ; then
+	echo "Tar archive, $tarfile, is currently a directory."
+	echo "Did you forget to add the archive name?"
+	minorusage
+	exit 1
 fi
 
 # doublecheck the file arguments
@@ -113,20 +127,18 @@ done
 
 # Give them time to Ctrl+C
 if $foundminus; then sleep 1; fi
-	
-# This failsafe works especially well at detecting when people forgot the archive name and jumped right to a list of dirs.
-if ! $notar && [ -d "$tarfile" ] ; then
-	echo "Tar archive, $tarfile, is currently a directory."
-	echo "Did you forget to add the archive name?"
-	exit 1
-fi
 
 # Allow the user to take back typos. Does not stop block devices because that's just annoying.
 if ! $force && ! $notar && [ -f "$tarfile" ]; then
-	echo "Tar archive, $tarfile, already exists. Overwrite? [y/N]: "
-	read line
-	if ! [[ "$line" =~ ^y|Y ]]; then
-		echo "Not overwriting $tarfile."
+	if [ -t 0 ] ; then
+		echo "Tar archive, $tarfile, already exists. Overwrite? [y/N]: "
+		read line
+		if ! [[ "$line" =~ ^y|Y ]]; then
+			echo "Not overwriting $tarfile."
+			exit 1
+		fi
+	else
+		echo "$tarfile already exists. Use --force to overwrite it."
 		exit 1
 	fi
 fi
