Added messages to the terminal

diff --git a/src/launch b/src/launch
--- a/src/launch
+++ b/src/launch
@@ -7,5 +7,7 @@ if [ $# -le 0 ] ; then
 fi
 
 mkdir -p ~/.log/
-daemon --inherit --safe -o ~/.log/launch-"$1".log -D "$PWD" -- $@
+daemon --inherit --safe -o ~/.log/launch-"$1".log -D "$PWD" -- $@ || ( echo "Failed to launch." && exit 2 )
+echo "Successfully launched. Output is appended to ~/.log/launch-$1.log"
+exit 0
 
diff --git a/src/persist b/src/persist
--- a/src/persist
+++ b/src/persist
@@ -16,11 +16,25 @@ case "$1" in
 		shift
 		mkdir -p ~/.log/
 		daemon --name="$COMM" --respawn --inherit --safe -o ~/.log/persist-"$COMM".log -D "$PWD" -- $@
+		if [ $? == 0 ] ; then
+			echo "Successfully launched. Output is appended to ~/.log/persist-$1.log"
+			exit 0
+		else
+			echo "Failed to launch."
+			exit 2
+		fi
 		;;
 	stop)
 		MODE=stop
 		shift
 		daemon --stop --name="$COMM"
+		if [ $? == 0 ] ; then
+			echo "Successfully stopped."
+			exit 0
+		else
+			echo "Failed to stop."
+			exit 2
+		fi
 		;;
 	*)
 		usage
