Persist now works much better, as does launch

diff --git a/src/launch b/src/launch
--- a/src/launch
+++ b/src/launch
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 set -e
 
 if [ $# -le 0 ] ; then
@@ -6,8 +6,9 @@ if [ $# -le 0 ] ; then
 	exit 1
 fi
 
+COMM="$(basename "$1")"
+LOG=~/.log/launch-"$COMM".log
 mkdir -p ~/.log/
-daemon --inherit --safe -o ~/.log/launch-"$1".log -D "$PWD" -- $@ || ( echo "Failed to launch." && exit 2 )
-echo "Successfully launched. Output is appended to ~/.log/launch-$1.log"
+daemon --inherit --safe -o "$LOG" -D "$PWD" -- launch-wrapper $@ || ( echo "Failed to launch." && exit 2 )
+echo "Successfully launched. Output is appended to ~/.log/launch-$COMM.log.lz4"
 exit 0
-
